#!/usr/bin/python2

from daemon.pidfile import PIDLockFile
from daemon import DaemonContext
from os.path import join, expanduser
from libmnem import Mnem, Dzen2
import signal
import sys
import time

dzen2 = Dzen2()
mnem  = Mnem(join(expanduser('~'), '.mnem.data'), dzen2)

def reload(*args):
    print 'Reloading data.'
    mnem.load()

def exit(*args):
    print 'Saving data.'
    mnem.save()
    sys.exit()

def dump(*args):
    print 'Saving data.'
    mnem.save()

mnem_pid = PIDLockFile(
join(expanduser('~'), '.mnem.pid'))

context = DaemonContext(pidfile = mnem_pid, 
stdout = sys.stdout, stderr = sys.stderr, 
signal_map = {signal.SIGTERM: exit, signal.SIGUSR2: dump,
signal.SIGUSR1: reload})

with context:
    print 'Daemon started.'
    mnem.mainloop()






