#!/usr/bin/python

from os.path import join, expanduser
from datetime import datetime
from libmn import Mnem
from daemon.pidfile import PIDLockFile
import argparse
import tempfile
import sys
import signal
import time
import os

def main():
    today  = datetime.today()
    mnem   = Mnem(join(expanduser('~'), 'mnem.db'))

    def find(args):
        for indi, indj in mnem.find(args.msg):
            print(indi, indj)
        
    parser = argparse.ArgumentParser()
    parser.add_argument('msg', nargs='?', help='Messages')

    parser.add_argument(
    '-i', '--minutes', 
    default=[today.minute],  type=int,
    nargs='*', help='List of minutes.')

    parser.add_argument(
    '-m', '--months',     
    default=[today.month],  type=int,
    nargs='*', help='List of months.')

    parser.add_argument(
    '-y', '--years', 
    default=[today.year], type=int,
    nargs='*', help='List of ears.')

    parser.add_argument(
    '-u', '--hours', 
    default=[today.hour],  type=int,
    nargs='*', help='List of hours.')

    parser.add_argument(
    '-d', '--days', default=[today.day],  type=int,
    nargs='*', help='List of days.')

    parser.add_argument('-a', '--add', dest='cmd', 
    action='store_const', const=lambda args: 
    mnem.add_note(args.msg, args.years, args.months, 
    args.days, args.hours, args.minutes), 
    help='Add a note.')

    parser.add_argument(
    '-f', '--find', dest='cmd', 
    action='store_const', const=find, 
    help='Find a note based on a regex.')

    parser.add_argument(
    '-r', '--remove', dest='cmd', 
    action='store_const', const=lambda args: 
    mnem.del_note(args.msg), 
    help='Remove a note based on a regex.')
    args = parser.parse_args()

    if args.cmd: 
        args.cmd(args)
    mnem.conn.close()

if __name__ == '__main__':
    main()
    # mnem_pid = PIDLockFile(join(tempfile.gettempdir(), 'mnem.pid'))
    # pid      = mnem_pid.read_pid()
    # os.kill(pid, signal.SIGUSR1)


