#!/usr/bin/python2

from daemon.pidfile import PIDLockFile
from daemon import DaemonContext
from os.path import join, expanduser
from mnemcore import Mnem, Dzen2
import signal
import tempfile
import sys
import time

dzen2 = Dzen2()
mnem  = Mnem(join(expanduser('~'), '.mnem.data'), dzen2)
mnem.load()

def reload(*args):
    mnem.load()

mnem_pid = PIDLockFile(
join(tempfile.gettempdir(), '.mnem.pid'))

context = DaemonContext(pidfile = mnem_pid, 
stdout = sys.stdout, stderr = sys.stderr, 
signal_map = {signal.SIGUSR1: reload})

with context:
    print 'Daemon started.'
    mnem.mainloop()













